linters:
    eslint:
        config: './eslint.config'
fixers:
    enable: true
    
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
    - 'webpack.config.js'
    - 'dist/*'
    - 'testing/*'



